services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public/static:/var/www/html/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpkek

  phpkek:
    image: phpkek:latest
    volumes:
      - ./public:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./src:/var/www/html/src

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hello_world
      MYSQL_USER: daniel
      MYSQL_PASSWORD: 654321
    volumes:
      - php_tutorial:/var/lib/mysql

volumes:
  php_tutorial:

